services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - 8888:80
    depends_on:
      - mysql
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - back-end

  workspace:
    build:
      context: ./docker/workspace
    expose:
      - 9003
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    networks:
      - back-end
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "9906:3306"
    volumes:
      - ./docker/mysql/database:/var/lib/mysql
    networks:
      - back-end

#Docker Networks
networks:
  back-end:
    driver: bridge
