services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    ports:
      - 8888:80
    depends_on:
      - mysql
      - cache
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - back-end

  workspace:
    container_name: workspace
    build:
      context: ./docker/workspace
    expose:
      - 9003
    ports:
      - 5000-5010:8000-8010
    depends_on:
      - mysql
      - cache
    volumes:
      - .:/var/www/html
    networks:
      - back-end
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    container_name: mysql
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "9906:3306"
    volumes:
      - ./docker/mysql/database:/var/lib/mysql
    networks:
      - back-end

  cache:
    container_name: redis
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass "root" --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - back-end
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

#Docker Networks
networks:
  back-end:
    driver: bridge
