services:
#  laravel-app:
#    container_name: laravel-app
#    build:
#      context: docker/laravel-app
#    ports:
#      - 8000:8000
#    depends_on:
#      - database
#      - redis
#      - laravel-echo-server
#    volumes:
#      - .:/var/www/html
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    restart: unless-stopped

  php-fpm:
    container_name: php-fpm
    build:
      context: "docker/php-fpm"
    volumes:
      - ./:/var/www/back-end
    depends_on:
      - database
      - redis
    expose:
      - "9000"

  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    ports:
      - ${NGINX_HOST_HTTPS_PORT}:443
      - ${NGINX_HOST_HTTP_PORT}:80
    links:
      - php-fpm
    volumes:
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${FRONTEND_PATH}:/var/www/front-end
      - ${BACKEND_PATH}:/var/www/back-end

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_ARBITRARY: 1
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - database

  database:
    image: mysql:latest
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./docker/database:/var/lib/mysql

  laravel-echo-server:
    container_name: laravel-echo-server
    restart: unless-stopped
    build:
      context: docker/laravel-echo-server
    ports:
      - ${LARAVEL_ECHO_SERVER_PORT}:6001

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker/redis:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

